---
- name: deploy HAProxy
  hosts: frontends
  gather_facts: false 
  become: true

  roles:
  - management
  - haproxy


- name: deploy app
  hosts: apps
  gather_facts: false
  become: true

  roles:
  - management
  - app

- name: deploy db
  gather_facts: false
  become: true
  hosts: appdbs

  roles:
  - management
  - db
