---
# tasks file for db
- name: install PostgreSQL
  yum:
    name: postgresql-server
    state: latest
    
- name: enable PostgreSQL at boot
  service:
    name: postgresql
    enabled: yes
    
- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: Ensure PostgreSQL database is initialized.
  command: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: "{{ postgresql_user }}"
  
- name: start PostgreSQL
  service:
    name: postgresql.service
    state: started
